# Generated by Django 4.2.7 on 2024-01-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0009_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
